---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-ops
  namespace: argocd
spec:
  description: Cluster Operations 
  sourceRepos:
  - 'https://github.com/timbohiatt/time-keeper-v3-ops'
  destinations:
  - namespace: '*'
    server: https://172.16.0.18
  - namespace: '*'
    server: https://192.168.0.2
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-bank-of-anthos
  namespace: argocd
spec:
  description: 'Bank of Anthos'
  sourceRepos:
  - 'https://github.com/timbohiatt/time-keeper-v3-apps-boa.git'
  destinations:
  - namespace: 'app-bank-of-anthos'
    server: https://172.16.0.18
  - namespace: 'app-bank-of-anthos'
    server: https://192.168.0.2
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-tell-the-time
  namespace: argocd
spec:
  description: 'Tell the Time'
  sourceRepos:
  - 'https://github.com/timbohiatt/time-keeper-v3-apps-ttt'
  destinations:
  - namespace: 'app-time-now'
    server: https://172.16.0.18
  - namespace: 'app-time-now'
    server: https://192.168.0.2
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-whereami
  namespace: argocd
spec:
  description: 'Where Am I?
  sourceRepos:
  - 'https://github.com/garybowers/whereami.git'
  destinations:
  - namespace: 'app-whereami'
    server: https://172.16.0.18
  - namespace: 'app-whereami'
    server: https://192.168.0.2
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
